[phases.setup]
aptPkgs = ["libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2t64", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libxrandr2", "libxcomposite1", "libxdamage1"]

[start]
cmd = "node server/index.js"
